</td>
</tr>
<tr>
<td height="2"></td>
</tr>
</table>

</td>
</tr>
</table>
</td>
<td valign="top" width="585"> 

<table width="97%" border="0" cellspacing="0" cellpadding="0" align="center">
<FORM METHOD="POST" ACTION="acc">
<tr bgcolor="#D0D0D0"> 
<td colspan="2"> 
<div align="center"><font color="#000000"> </font> 
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr> 
<td width="1%" align="right" class="top-left"> 
<br></td>
<td class="top">Account Creation</td>
<td width="1%" align="right" class="top-right"> 
<br></td>
</tr>
</table>
</div>
</td>
</tr>
<tr bgcolor="#FFFFFF"> 
<td width="1%" class="top-left-bottom">&nbsp;</td>
<td class="top-right-bottom">

Please fill in your desired username and password as well as a e-mail address.</td></tr>
<tr>
  <td align="center" colspan="2"><table 

width="100%" cellspacing="0" cellpadding="0" align="center" class="left-bottom-right"><tr 

bgcolor="#D0D0D0"><td width="5"><font color="#D0D0D0">|</font></td><td 
align="left" width="15%">&nbsp;</td><td align="center">&nbsp;</td><td align="right" 
width="10%"></td><td 

width="5"></td></tr></table></td>
</tr>
<tr>
<td colspan="2"> 
&nbsp;<div align="center"> 
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr> 
<td width="1%" align="right" class="top-left" style="border-right-color: #000000; border-bottom-color: #000000" bgcolor="#C0C0C0"> 
<br></td>
<td class="top" style="border-left-color: #000000; border-right-color: #000000; border-bottom-color: #000000" bgcolor="#C0C0C0">
Application</td>
<td width="1%" align="right" class="top-right" bgcolor="#C0C0C0" style="border-left-color: #000000; border-bottom-color: #000000"> 
<br></td>
</tr>
</table>
</div>
</td>
</tr>
<tr>
<td width="1%" class="top-left-bottom">&nbsp;</td>
<td class="top-right-bottom">

&nbsp;<blockquote>
  <p>username:<font color="#000000">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<input type="text" name="uname" size="20"></font></p>
  <p>password:<font color="#000000">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<input type="password" name="pword" size="20"></font></p>
  <p>confirm password:<font color="#000000">&nbsp;
<input type="password" name="pword" size="20"></font></p>
          <p>e-mail:<font color="#000000">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
            <input type="text" name="e-mail" size="20">
            </font></p>
          <p><font color="#000000">first name: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
            <input type="text" name="fname">
            </font></p>
          <p><font color="#000000">last name:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" name="lname">
 </font></p>
  <p> 
<font color="#000000">
<input type="submit" name="signup" value="create" class="x4u"></font></p>
</blockquote>
</td>
</tr>
<tr><td align="center" colspan="2"><table 

width="100%" cellspacing="0" cellpadding="0" align="center" class="left-bottom-right"><tr 

bgcolor="#D0D0D0"><td width="5"><font color="#D0D0D0">|</font></td><td 
align="left" width="15%"><font 

color="#000000"></font></td><td align="center"><font color="#000000"></font></td><td align="right" 
width="10%"></td><td 

width="5"></td></tr></form></table></td>
</tr>
</table>
</td>




<tr> 
<td colspan="2">&nbsp;</td>
</tr>
<tr> 
<td colspan="2"><table width="100%" cellpadding="0" cellspacing="0" bgcolor="#D0D0D0"><tr 

height="1"><td bgcolor="#D0D0D0"></td></tr></table>
</td>
</tr>


<center><span style="font-family: Verdana; font-size: 7.5pt; color: #000000">copyright 

(C) 2003 DSO Engine Sever, all rights reserved.<BR>designed by
<a href="mailto:admin@gameserver.com">DSO Team</a>.




</span></center>
</body>