</td>
</tr>
<tr>
<td height="2"></td>
</tr>
</table>

</td>
</tr>
</table>
</td>
<td valign="top" width="585"> 

<table width="97%" border="0" cellspacing="0" cellpadding="0" align="center">
<tr bgcolor="#D0D0D0"> 
<td colspan="3"> 
<div align="center"><font color="#000000"> </font> 
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr> 
<td width="1%" align="right" class="top-left"> 
<br></td>
<td class="top">Main Screen</td>
<td width="1%" align="right" class="top-right"> 
<br></td>
</tr>
</table>
</div>
</td>
</tr>
<tr bgcolor="#FFFFFF"> 
<td width="1%" class="top-left-bottom">&nbsp;</td>
<td class="top-right-bottom">
There has been an error in your account creation: your password does not match!</td></tr><tr><td align="center" colspan="6"><table 

width="100%" cellspacing="0" cellpadding="0" align="center" class="left-bottom-right"><tr 

bgcolor="#D0D0D0"><td width="5"><font color="#D0D0D0">|</font></td><td 
align="left" width="15%"><font 

color="#000000"></td><td align="center"><font color="#000000"></font></td><td align="right" 
width="10%"></font></td><td 

width="5"></td></tr></table></td>
</tr>
</table>
</td>
</tr>
</table>
</td>
</tr>
<tr> 
<td colspan="2">&nbsp;</td>
</tr>
<tr> 
<td colspan="2"><table width="100%" cellpadding="0" cellspacing="0" bgcolor="#D0D0D0"><tr 

height="1"><td bgcolor="#D0D0D0"></td></tr></table>
</td>
</tr>

</table>
<center><span style="font-family: Verdana; font-size: 7.5pt; color: #000000">copyright 

(C) 2003 DSO Engine Sever, all rights reserved.<BR>designed by
<a href="mailto:jarad@nix.org">DSO Team</a>.




</span></center>
</body>